      IF (IPOT.EQ.1) THEN
        LZINDO = .TRUE.
        WRITE (*,*) ' ZINDO POTENTIAL BEING USED '
      ELSEIF (IPOT.EQ.2) THEN
        LENJON  = .TRUE.
        WRITE (*,*) ' LENNARD JONES POTENTIAL BEING USED '
      ELSEIF (IPOT.EQ.3) THEN
        LMOPAC  = .TRUE.
        WRITE (*,*) ' MOPAC POTENTIAL BEING USED '
      ELSEIF (IPOT.EQ.4) THEN
        WRITE (*,*) ' STILLINGER-WEBER POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.5) THEN
        WRITE (*,*) ' HOUFENG POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.6) THEN
        LZINDO = .TRUE.
        LCOMPOT= .TRUE.
        WRITE (*,*) ' COMBINED ZINDO/HFD POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.7) THEN
        LCOMPOT= .TRUE.
        WRITE (*,*) ' COMBINED MOPAC/SW POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.8) THEN
        WRITE (*,*) ' MPB DIAMOND POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.9) THEN
        WRITE (*,*) ' DIAMOND POTENTIAL BASED ON AM1 BEING USED'
      ELSEIF (IPOT.EQ.10) THEN
        LCOMPOT= .TRUE.
        WRITE (6,*) ' DIAMOND POTENTIAL BASED ON PM3 BEING USED'
      ELSEIF (IPOT.EQ.11) THEN
        LCOMPOT= .TRUE.
        WRITE (*,*) ' COMBINED MOPAC/MORSE POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.12) THEN
	  WRITE (*,*) ' MORSE POTENTIAL BEING USED'
      ELSEIF (IPOT.EQ.15) THEN
        LCOMPOT= .TRUE.
        WRITE (*,*) ' COMBINED MOPAC/MORSE POTENTIAL BEING USED'
      ELSE   
        WRITE (*,*) ' NO POTENTIAL SET '

        STOP
      ENDIF
